image: Visual Studio 2015

before_build:
- cmd: set
- ps: Start-FileDownload 'https://github.com/zhang-ray/opus/releases/download/1.0.3/opus-112-win32-build.7z'
- 7z x opus-112-win32-build.7z
- ps: Start-FileDownload 'https://github.com/zhang-ray/portaudio/releases/download/1.0.4/pa19-win32-x86-release-build.7z'
- 7z x pa19-win32-x86-release-build.7z
- cmd: copy /y .\build\Release\portaudio_static_x86.lib .\portaudio_static_x86.lib
- mkdir ..\build\ && cd ..\build\
- cmake ..\easy-voice-call

configuration:
  - Release

build:
  project: ..\build\EVC.sln
  parallel: true
  #verbosity: quiet

after_build:
- cd ..\easy-voice-call
- copy /y 
- 7z a build.VS2015.7z ..\build\

artifacts:
- path: .\build.VS2015.7z


#image: ubuntu
#build_script:
#- ./scripts/ubuntu.build.sh

#test_script:
#- pwd
#- ../easy-voice-call-build/tests/unit_tests/Opus
