image: Visual Studio 2015

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

before_build:
- git clone https://github.com/zhang-ray/audio-processing-module
- cd ..
- ps: Start-FileDownload 'https://github.com/zhang-ray/opus/releases/download/1.0.5/opus-112-win32-build.7z'
- 7z x opus-112-win32-build.7z
- ps: Start-FileDownload 'https://github.com/zhang-ray/portaudio/releases/download/1.0.4/pa19-win32-x86-release-build.7z'
- 7z x pa19-win32-x86-release-build.7z
- mkdir include\boost
- mkdir easy-voice-call-build\ && cd easy-voice-call-build\
- cmake -Wno-dev ..\easy-voice-call

configuration:
  - Release

build:
  project: ..\easy-voice-call-build\easy-voice-call.sln
  parallel: true
  verbosity: quiet


test_script:
- set PATH=%PATH%;C:\Libraries\boost_1_67_0\lib32-msvc-14.0;C:\projects\easy-voice-call-build\client_essential\Release;
- ..\easy-voice-call-build\tests\sanity_check\Release\sanity_check_audio.exe


after_test:
- mkdir artifacts
- copy C:\Libraries\boost_1_67_0\lib32-msvc-14.0\boost_date_time-vc140-mt-x32-1_67.dll          artifacts\
- copy C:\Libraries\boost_1_67_0\lib32-msvc-14.0\boost_filesystem-vc140-mt-x32-1_67.dll         artifacts\
- copy C:\Libraries\boost_1_67_0\lib32-msvc-14.0\boost_log-vc140-mt-x32-1_67.dll                artifacts\
- copy C:\Libraries\boost_1_67_0\lib32-msvc-14.0\boost_system-vc140-mt-x32-1_67.dll             artifacts\
- copy C:\Libraries\boost_1_67_0\lib32-msvc-14.0\boost_thread-vc140-mt-x32-1_67.dll             artifacts\
- copy .\client_essential\Release\client_essential.dll  artifacts\
- copy .\client_cli\Release\client_cli.exe              artifacts\EasyVoiceCall.Client.Cli.exe
- copy .\client_qt5\Release\client_qt5.exe              artifacts\EasyVoiceCall.exe
- copy .\server\Release\server.exe                      artifacts\EasyVoiceCall.Server.Windows.exe
- C:\Qt\5.11\msvc2015\bin\windeployqt.exe               artifacts\EasyVoiceCall.exe
- copy ..\easy-voice-call\scripts\EasyVoiceCall.nsi .
- makensis EasyVoiceCall.nsi
- move EasyVoiceCall.Client.Windows.Installer.exe ..\easy-voice-call\
- move .\server\Release\server.exe ..\easy-voice-call\EasyVoiceCall.Server.Windows.exe
- # extra sanity check
- cmd: .\artifacts\EasyVoiceCall.exe


artifacts:
- path: EasyVoiceCall.Client.Windows.Installer.exe
- path: EasyVoiceCall.Server.Windows.exe

deploy:
  provider: GitHub
  auth_token:
    secure: PiQDTyaNV3HdYRawTlwyD/bsMbpBg2Kx+/BEUEz9qOasvZlDBmxj3tFB0bNYwXIc
  artifact: EasyVoiceCall.Client.Windows.Installer.exe
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
