image: Visual Studio 2015

before_build:
- git clone https://github.com/zhang-ray/audio-processing-module
#- cmd: tree /F C:\Libraries\boost_1_67_0 
#- cmd: tree /F C:\Qt\5.11.1\msvc2015
- cd ..
- ps: Start-FileDownload 'https://github.com/zhang-ray/opus/releases/download/1.0.5/opus-112-win32-build.7z'
- 7z x opus-112-win32-build.7z
- ps: Start-FileDownload 'https://github.com/zhang-ray/portaudio/releases/download/1.0.4/pa19-win32-x86-release-build.7z'
- 7z x pa19-win32-x86-release-build.7z
- mkdir include\boost
#- xcopy C:\Libraries\boost_1_67_0\boost include\boost /E # shorten building time
#- xcopy C:\Libraries\boost_1_67_0\lib32-msvc-14.0 C:\projects\build\Release /E # shorten building time
- mkdir easy-voice-call-build\ && cd easy-voice-call-build\
- cmake -Wno-dev ..\easy-voice-call

configuration:
  - Release

build:
  project: ..\easy-voice-call-build\easy-voice-call.sln
  parallel: true
  #verbosity: quiet

after_build:
- cd client_qt5
- xcopy C:\Libraries\boost_1_67_0\lib32-msvc-14.0\boost_system-vc140-mt-x32-1_67.dll Release\
- C:\Qt\5.11.1\msvc2015\bin\windeployqt.exe Release\client_qt5.exe
- rename Release EasyVoiceCall.win32
- 7z a ..\..\easy-voice-call\EasyVoiceCall.win32.zip EasyVoiceCall.win32

artifacts:
- path: EasyVoiceCall.win32.zip

deploy:
  provider: GitHub
  auth_token:
    secure: PiQDTyaNV3HdYRawTlwyD/bsMbpBg2Kx+/BEUEz9qOasvZlDBmxj3tFB0bNYwXIc
  artifact: EasyVoiceCall.win32.zip
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only

#image: ubuntu
#build_script:
#- ./scripts/ubuntu.build.sh

#test_script:
#- pwd
#- ../easy-voice-call-build/tests/unit_tests/Opus
