image: Visual Studio 2015

before_build:
- cmd: tree /F C:\Libraries\boost_1_67_0 
- cmd: tree /F C:\Qt\5.11.1\msvc2015
- cd ..
- ps: Start-FileDownload 'https://github.com/zhang-ray/opus/releases/download/1.0.5/opus-112-win32-build.7z'
- 7z x opus-112-win32-build.7z
- ps: Start-FileDownload 'https://github.com/zhang-ray/portaudio/releases/download/1.0.4/pa19-win32-x86-release-build.7z'
- 7z x pa19-win32-x86-release-build.7z
- mkdir include\boost
- xcopy C:\Libraries\boost_1_67_0\boost include\boost /E
- xcopy C:\Libraries\boost_1_67_0\lib32-msvc-14.0 C:\projects\build\Release /E
- mkdir easy-voice-call-build\ && cd easy-voice-call-build\
- cmake ..\easy-voice-call

configuration:
  - Release

build:
  project: ..\easy-voice-call-build\easy-voice-call.sln
  parallel: true
  #verbosity: quiet

after_build:
- cd ..\easy-voice-call
- xcopy C:\Libraries\boost_1_67_0\lib32-msvc-14.0\boost_log-vc140-mt-x32-1_67.dll    ..\easy-voice-call-build\src\Release\
- xcopy C:\Libraries\boost_1_67_0\lib32-msvc-14.0\boost_system-vc140-mt-x32-1_67.dll ..\easy-voice-call-build\src\Release\
- 7z a vc140-mt-x32.7z ..\easy-voice-call-build\src\Release

artifacts:
- path: .\vc140-mt-x32.7z


#image: ubuntu
#build_script:
#- ./scripts/ubuntu.build.sh

#test_script:
#- pwd
#- ../easy-voice-call-build/tests/unit_tests/Opus
