image: Visual Studio 2015

before_build:
- cmd: set
- ps: Start-FileDownload 'https://github.com/zhang-ray/opus/releases/download/1.0.3/opus-112-win32-build.7z'
- 7z x opus-112-win32-build.7z
- cmd: copy /y .\VS2010\Win32\Debug\opus.lib C:\Windows\system32\opus.lib
- ps: Start-FileDownload 'https://github.com/zhang-ray/portaudio/releases/download/1.0.4/pa19-win32-x86-release-build.7z'
- 7z x pa19-win32-x86-release-build.7z
- cmd: copy /y .\build\Release\portaudio_x86.dll C:\Windows\system32\portaudio_x86.dll
- cmd: copy /y .\build\Release\portaudio_x86.lib C:\Windows\system32\portaudio_x86.lib
- cmd: dir C:\Windows\system32\
- mkdir ..\build\ && cd ..\build\
- cmake ..\easy-voice-call

build:
  project: ..\build\EVC.sln
  parallel: true
  #verbosity: quiet

after_build:
- cd ..\audio-processing-module
- 7z a Debug.VS2015.7z ..\build\src\Debug

artifacts:
- path: .\Debug.VS2015.7z


#image: ubuntu
#build_script:
#- ./scripts/ubuntu.build.sh

#test_script:
#- pwd
#- ../easy-voice-call-build/tests/unit_tests/Opus
