image: Visual Studio 2015

before_build:
- wget https://github.com/zhang-ray/opus/releases/download/1.0.3/opus-112-win32-build.7z
- 7z x opus-112-win32-build.7z
- mkdir ..\build\ && cd ..\build\
- cmake ..\easy-voice-call

build:
  project: ..\build\EVC.sln
  parallel: true
  #verbosity: quiet

after_build:
- cd ..\audio-processing-module
- 7z a Debug.VS2015.7z ..\build\src\Debug

artifacts:
- path: .\Debug.VS2015.7z


#image: ubuntu
#build_script:
#- ./scripts/ubuntu.build.sh

#test_script:
#- pwd
#- ../easy-voice-call-build/tests/unit_tests/Opus
