os: osx
language: cpp
sudo: required
# script: ./scripts/mac.build.sh && ../easy-voice-call-build/./tests/unit_tests/Opus
script: brew install qt && mdfind -name macdeployqt -onlyin /usr/local/Cellar/qt/
# deploy:
#   provider: releases
#   api_key: "GITHUB OAUTH TOKEN"
#   file: "FILE TO UPLOAD"
#   skip_cleanup: true
#   on:
#     tags: true