os: osx
language: cpp
sudo: required
# script: ./scripts/mac.build.sh && ../easy-voice-call-build/./tests/unit_tests/Opus
script: brew install qt && /usr/local/Cellar/qt/5.11.2/bin/macdeployqt

# deploy:
#   provider: releases
#   api_key: "GITHUB OAUTH TOKEN"
#   file: "FILE TO UPLOAD"
#   skip_cleanup: true
#   on:
#     tags: true